[package]
name = "bitcoin-pro"
description = "Professional bitcoin accounts & assets management"
version = "0.1.0-alpha.1"
authors = ["Dr Maxim Orlovsky <orlovsky@pandoracore.com>"]
edition = "2018"
license = "AGPL-3.0-only"
readme = "README.md"
exclude = ["test"]

[[bin]]
name = "bitcoin-pro"

[dependencies]
amplify = { version = "~2.3.1", features = ["serde"] }
amplify_derive = "~2.3.1"
lazy_static = "~1.4.0"
serde = { version = "~1.0.106", features = ["derive"] }
serde_with = { version = "~1.5.1", features = ["hex"] }
serde_json = "~1.0.59"
serde_yaml = "~0.8.14"
toml = "~0.5.7"
gtk = { version = "~0.9.2", features = ["v3_24_9"] }
gdk = { version = "~0.13.2", features = ["v3_24"] }
gio =  { version = "~0.9.1", features = ["v2_64"] }
glib = { version = "~0.10.3", features = ["v2_64"] }
glade = "~0.1.0-alpha.2"
lnpbp = { version = "~0.2.0-beta.2", features = ["lnp", "rgb", "tor", "url", "keygen", "elgamal"] }
lnpbp_derive = "~0.2.0-beta.2"
# rgb_node = { version = "~0.2.0-beta.3" }

[patch.crates-io]
# Remove this once https://github.com/jean-airoldie/zeromq-src-rs/pull/15 got merged
zeromq-src = { git = "https://github.com/LNP-BP/zeromq-src-rs", branch = "fix/cmake" }
