[package]
name = "bitcoin-pro"
description = "Professional bitcoin accounts & assets management"
version = "0.1.0-beta.2"
authors = ["Dr Maxim Orlovsky <orlovsky@pandoracore.com>"]
edition = "2018"
license = "AGPL-3.0-only"
readme = "README.md"
exclude = ["examples"]

[[bin]]
name = "bitcoin-pro"

[dependencies]
amplify = { version = "3", features = ["serde"] }
amplify_derive = "2.4.2"
internet2 = { version = "0.3", features = [] }
lnpbp = "0.3"
descriptor-wallet = "0.3"
rgb-core = { version = "0.3.0-beta.3", git = "https://github.com/rgb-org/rgb-core" }
rgb20 = { version = "0.3.0-beta.3", git = "https://github.com/rgb-org/rgb-core" }
slip132 = "0.3.0-rc.1"
bitcoin = "0.26"
miniscript = "5"
lazy_static = "1.4"
serde = { version = "1", features = ["derive"] }
serde_with = { version = "1.5", features = ["hex"] }
serde_json = "1"
serde_yaml = "0.8"
toml = "0.5"
gtk = { version = "0.9.2", features = ["v3_24_9"] }
gdk = { version = "0.13.2", features = ["v3_24"] }
gio =  { version = "0.9.1", features = ["v2_64"] }
glib = { version = "0.10.3", features = ["v2_64"] }
glade = "0.1.0-alpha.3"
electrum-client = { version = "0.5.0-beta.1", git = "https://github.com/LNP-BP/rust-electrum-client", branch = "bitcoin-0.26" }

[workspace]
members = [".", "bpro"]
default-members = [".", "bpro"]
